name: mapingo_app
description: "Mapingo - Learn the states of Mexico by playing."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Navigation
  go_router: ^14.8.1
  
  # Backend
  supabase_flutter: ^2.8.4

  # Local Settings
  shared_preferences: ^2.5.5

  # SVG Support
  flutter_svg: ^2.0.10

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
